# Project Name
TARGET = musique-crazy-frog

# Sources
CPP_SOURCES = musique-crazy-frog.cpp 

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

